### ISSUE TITLE
Protocol Enumerable not Implemented for Phoenix.LiveView.AsyncResult

### ISSUE THREAD

**Issue by 3even** [JohnElmLabs/AsyncAssigns#1]
Getting the following error when visiting the root path.

```
# Protocol.UndefinedError at GET /

Exception:

    ** (Protocol.UndefinedError) protocol Enumerable not implemented for %Phoenix.LiveView.AsyncResult{ok?: false, loading: [:all_users], failed: nil, result: nil} of type Phoenix.LiveView.AsyncResult (a struct)
        (elixir 1.14.5) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir 1.14.5) lib/enum.ex:166: Enumerable.reduce/3
        (elixir 1.14.5) lib/enum.ex:4307: Enum.reduce/3
        (async_assign 0.1.0) lib/async_assign_web/live/users_live.ex:64: anonymous fn/2 in AsyncAssignWeb.UsersLive.render/1
        (phoenix_live_view 0.20.0) lib/phoenix_live_view/diff.ex:386: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.20.0) lib/phoenix_live_view/diff.ex:538: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.20.0) lib/phoenix_live_view/diff.ex:384: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.20.0) lib/phoenix_live_view/diff.ex:136: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.20.0) lib/phoenix_live_view/static.ex:251: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.20.0) lib/phoenix_live_view/static.ex:134: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.20.0) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.7) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
        (async_assign 0.1.0) lib/async_assign_web/endpoint.ex:1: AsyncAssignWeb.Endpoint.plug_builder_call/2
        (async_assign 0.1.0) deps/plug/lib/plug/debugger.ex:136: AsyncAssignWeb.Endpoint."call (overridable 3)"/2
        (async_assign 0.1.0) lib/async_assign_web/endpoint.ex:1: AsyncAssignWeb.Endpoint.call/2
        (phoenix 1.7.7) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.10.0) /home/***/Projects/phoenix-apps/AsyncAssigns/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /home/***/Projects/phoenix-apps/AsyncAssigns/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
```

My system:
```
Elixir:    1.14.5-otp-26  
Erlang:    26.0.1
OS:        Ubuntu 22.04.3 LTS  
```

**Comment by forgauravs** [comment]
hii.. any fix for the above issue ?

**Comment by John-Elm** [comment]
Hi @3even @forgauravs ,

I apologize that I'm just now seeing this issue.

This has been resolved -- The latest master has everything working properly

**Comment by forgauravs** [comment]
Awesome .. thanks .
Great to hear from you.
Best regards,Gourav S


Sent from Yahoo Mail for iPhone


On Thursday, November 9, 2023, 7:11 AM, John Elm ***@***.***> wrote:




Hi @3even @forgauravs ,

I apologize that I'm just now seeing this issue.

This has been resolved
